name: 'Build CA Certificates Debian Package'

on:
  workflow_call:

jobs:
  check-ca-certificates:
    name: "Check ca-certificates"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./linux

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          java-package: jdk
          architecture: x64
          distribution: 'temurin'

      - name: Build
        run: |
          export _JAVA_OPTIONS="-Xmx4G"
          ./gradlew --parallel :ca-certificates:check --stacktrace

      - uses: actions/upload-artifact@v3
        if: always() # always run even if the previous step fails
        with:
          name: test-results
          path: '**/build/test-results/**/TEST-*.xml'

      - uses: actions/upload-artifact@v3
        with:
          name: ca-certificates
          path: '**/build/ospackage/adoptium-ca-certificates_*.deb'