name: Code Freeze Bot

# Controls when the workflow will run
on:
  pull_request_target:
    branches: [ "master" ]

jobs:
  codefreeze:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.pull_request_target.number }}"
